name: google_news
description: Brief News - A google news app which will show you latest news based on category from all around the world. Brief News. Short News. Google News. inshorts. India News. Flutter News. Latest News. BN. Top headlines. 60 words news. Tookma.
version: 1.0.2+10

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  webview_flutter: ^0.3.18+1
  double_back_to_close_app: ^0.1.2
  firebase_admob: ^0.9.0+10
  flutter_launcher_icons: ^0.7.2
  onesignal_flutter: ^2.0.0
  facebook_audience_network: ^0.4.0
  # device_id: ^0.2.0

  # A powerful Http client for Dart, which support interceptors, FormData, Request Cacellation,
  # File Downloading, Timeout, etc...
  dio: ^3.0.3

  # Flutter widgets that makes it  easy to implement the BLoC design pattern
  flutter_bloc: ^3.0.0

  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^3.2.3

  # Package provides internalization and localization facilites, including message translation,
  # plurals and genders, date/number formatting and parsing and bidirectional text
  intl: ^0.16.0

  # Flutter plugin for launching and URL in the mobile platform
  url_launcher: ^5.2.0

  # Flutter library to load and cache network images
  # cached_network_image: ^2.0.0-rc

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Tools to write binaries that run builders.
  build_runner: ^1.7.1

flutter:
  uses-material-design: true
  assets:
   - assets/images/
  #  - images/a_dot_ham.jpeg

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/new_icon.png'
  adaptive_icon_background: '#ffffff'

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
